kind = "web"
previewPath = "/"
title = "WebGIS Maluku Tengah"
version = "1.0.0"
id = "artifacts/webgis-maluku"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18745

[services.development]
run = "pnpm --filter @workspace/webgis-maluku run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/webgis-maluku", "run", "build" ]
publicDir = "artifacts/webgis-maluku/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18745"
BASE_PATH = "/"
